//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertTechWatchBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertTechWatchBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blink 10 times by closing your eyes as if falling asleep (very slowly) 😉.
        /// </summary>
        internal static string Instruction1 {
            get {
                return ResourceManager.GetString("Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥂 Cheers to all the people working on their dreams and not for the Weekend.
        /// </summary>
        internal static string Instruction10 {
            get {
                return ResourceManager.GetString("Instruction10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Winner is just a Looser who tried one more time! blink :).
        /// </summary>
        internal static string Instruction11 {
            get {
                return ResourceManager.GetString("Instruction11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe we are not the most Talented one, but we are the Hardest Worker in the room 💪🏻.
        /// </summary>
        internal static string Instruction12 {
            get {
                return ResourceManager.GetString("Instruction12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d rather regret the things i have done than the things that i haven&apos;t.
        /// </summary>
        internal static string Instruction13 {
            get {
                return ResourceManager.GetString("Instruction13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone wants to be successful, until they see what it actually takes!.
        /// </summary>
        internal static string Instruction14 {
            get {
                return ResourceManager.GetString("Instruction14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you knew me yesterday, you don&apos;t know me anymore; i grow Daily.
        /// </summary>
        internal static string Instruction15 {
            get {
                return ResourceManager.GetString("Instruction15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاف بشین!.
        /// </summary>
        internal static string Instruction16 {
            get {
                return ResourceManager.GetString("Instruction16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الان طبعاً باید صاف نشسته باشی!.
        /// </summary>
        internal static string Instruction17 {
            get {
                return ResourceManager.GetString("Instruction17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آب آب؛ بدن الان یه لیوان آب لازم داره.
        /// </summary>
        internal static string Instruction18 {
            get {
                return ResourceManager.GetString("Instruction18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check out what&apos;s going on 20 feet away from you.
        /// </summary>
        internal static string Instruction2 {
            get {
                return ResourceManager.GetString("Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get plenty of vitamins  🥕 🍊 🍋.
        /// </summary>
        internal static string Instruction3 {
            get {
                return ResourceManager.GetString("Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wet  your eyes with cold and clean water 💦💦💦.
        /// </summary>
        internal static string Instruction4 {
            get {
                return ResourceManager.GetString("Instruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God gives you power 💪🏻.
        /// </summary>
        internal static string Instruction5 {
            get {
                return ResourceManager.GetString("Instruction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never hurt animals 🐿 and dont forget to blink.
        /// </summary>
        internal static string Instruction6 {
            get {
                return ResourceManager.GetString("Instruction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ☄️     Oh look there is a comet!, Make a wish, now!.
        /// </summary>
        internal static string Instruction7 {
            get {
                return ResourceManager.GetString("Instruction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👨🏻 ☝ first safety then work!.
        /// </summary>
        internal static string Instruction8 {
            get {
                return ResourceManager.GetString("Instruction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagine Walking in the jungle ... its raining ⛈ 🍀🌿⛈ 🌲🌴⛈.
        /// </summary>
        internal static string Instruction9 {
            get {
                return ResourceManager.GetString("Instruction9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 435780973.
        /// </summary>
        internal static string MiladsTlgID {
            get {
                return ResourceManager.GetString("MiladsTlgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll remind you to care for your eyes every 20 minutes  😏.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
